### ISSUE TITLE
webm tokens not showing in up in portrait

### ISSUE THREAD

**Issue by Ikabodo** [nickelpro/simply-portraits#2]
Animated tokens doesn't seem to work as portraits.
![image](https://user-images.githubusercontent.com/7766890/196928978-0f54d7ef-c88b-4b6c-adea-4aae650a2450.png)

**Comment by nickelpro** [comment]
That's because I'm naively using an `<img>` tag on the clearly mistaken assumption that people only use images.

This is fixable, just need to detect media type and do the right thing

**Comment by nickelpro** [comment]
Ok, I have a basic fix for this.

You think that animated tokens should autoplay/loop in chat or should they be static on their first frame?

**Comment by Ikabodo** [comment]
Since this modules aim is to be simple, I'd say just freeze it on the first frame. :) It's too small to appriciate animation anyway.

**Comment by nickelpro** [comment]
I'm not fundamentally opposed to adding options, but for now I'll leave it freezed. Something to do in the future. Fixed in next release
