### ISSUE TITLE
Simply Char Portraits too small for player who can't see well

### ISSUE THREAD

**Issue by SirAron111** [nickelpro/simply-portraits#3]
Is it possible to at least add an option to scale the chat portraits pixel size? And make it, so it doesn't interfere with the text itself, other than shifting it to the side. It seems to also block the tokens name coloration from midi-ql?

**Comment by nickelpro** [comment]
I copied the default size from the chat-portraits module, I'm happy to add an option to make the size configurable.

Would you like the option to be per-client or controlled by the DM? And can you perhaps include a screenshot of the conflict you're having with midi-qol?

**Comment by SirAron111** [comment]
Controlled by the DM is better for most, since that allows these things to be preset and everyone sees the same when things are described. But since there are modules that allow one to force client settings etc, it could also be individual. if you copied it from chat portraits mod, it's probably set to 36 pixels i usually set it to 50 pixels since i don't need all the functions chat portraits provides i wanted to switch to this lighter version (gotta reduce network traffic as much as possible when self-hosting).
![Unbenannt](https://user-images.githubusercontent.com/39855956/197214127-5a1a1d82-b32e-43d0-82b8-eaaeaaf5a4b7.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/39855956/197214134-df02451e-1322-4ecb-9e13-f5a724ff5f58.PNG)
Also, here are the screenshots. The midi -ql settings are the same in both pictures (set to make border and name the player color)
But with portrait mod enabled, it seems to overwrite the coloring it's not a terrible conflict to live with, just thought I report it.

**Comment by nickelpro** [comment]
Oh weird, I'll check it out this afternoon, thanks for the report

**Comment by nickelpro** [comment]
Fixed in v1.2.1

The color issue isn't on my end, it's a Midi-QOL bug, opened here: https://gitlab.com/tposney/midi-qol/-/issues/1043

**Comment by nickelpro** [comment]
This is now fixed in midi-qol 10.0.17+
