### ISSUE TITLE
Bug: Portrait missing with wildcard actors

### ISSUE THREAD

**Issue by Ikabodo** [nickelpro/simply-portraits#4]
When a token has a wildcard setting, the mod fails to find the an image. It instead looks for: `Druid_Medium_Humanoid_A_*.png:1` for example.

Suggested solutions:
1. Pick the first wildcard option.
OR
2. Pick the image from the token and not the original actor in this specific case.

**Comment by nickelpro** [comment]
Ya I know about this bug, the solution is the same as what midi-qol and chat-portraits does. I need to hook on `preCreateChatMessage` and attach the texture used by the generating speaker onto the message data. This has the added advantage of working regardless of what happens to the token or actor after the message is created, and the disadvantage of dirtying the message data even more than it already is.

**Comment by nickelpro** [comment]
Fixed in v1.2, doesn't work retroactively (only will be applied to new messages)
