### ISSUE TITLE
Minor bug, error with Dfreds Convenient effect

### ISSUE THREAD

**Issue by Ikabodo** [nickelpro/simply-portraits#5]
Might be worth adding some sort of check for messages that has no tokens, just to avoid error spamming.
As in, if the message has no token or actor, just ignore adding an image to suppress errors.

![image](https://user-images.githubusercontent.com/7766890/197843067-2e06151a-9c87-4eaf-a7ea-7d104c5d6369.png)

**Comment by nickelpro** [comment]
Module is supposed to do that already, but I missed this case where the chat comes from a non-existent scene as well. Will be fixed in next release

**Comment by nickelpro** [comment]
I really appreciate these reports helping me polish this little module

**Comment by Ikabodo** [comment]
I'm doing the easy part, you are doing all the great work. :)

**Comment by nickelpro** [comment]
Fixed, hopefully, in v1.2.2
