### ISSUE TITLE
No portrait appears if the player does not have a token on the current scene

### ISSUE THREAD

**Issue by cs96and** [nickelpro/simply-portraits#6]
If the player does not have a token on the current scene, then no portrait appears on their chat messages.  Maybe you could fallback to using their portrait image if no token is found (this may be dnd5e specific though, but am not 100% sure).

**Comment by nickelpro** [comment]
It's a little tricky, because right now we're doing the simple thing of looking up the token/scene presented by the message data. If the message data gave us a concrete actor this would be easier.

Thanks for the report, I'll brainstorm on this

**Comment by nickelpro** [comment]
Fix works for actors with prototype tokens. Doesn't fall back to portrait image just yet because I want to think of a consistent way to present the option "prefer actor portraits or prefer token images"
